kind: ServiceAccount
apiVersion: v1
metadata:
  name: cb-op-svc-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cb-op-cluster-role
rules:
- apiGroups:
  - couchbase.com
  resources:
  - couchbaseclusters
  verbs:
  - "*"
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - "get"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - secrets
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - "get"
  - "watch"
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
---
RoleBinding:
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cb-op-rb-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cb-op-cluster-role
subjects:
- kind: ServiceAccount
  name: cb-op-svc-account

  namespace: default
