apiVersion: couchbase.database.couchbase.com/v1beta1
kind: CouchbaseCluster
metadata:
  name: cb-cluster-member
spec:
  baseImage: couchbase/server
  version: enterprise-5.1.0
  authSecret: $SECRET_NAME
  exposeAdminConsole: true
  cluster:
    dataServiceMemoryQuota: $DATA_SVC_QUOTA
    indexServiceMemoryQuota: $IDX_SVC_QUOTA
    searchServiceMemoryQuota: $SRC_SVC_QUOTA
    indexStorageSetting: memory_optimized
    autoFailoverTimeout: 5
  buckets:
    - name: default
      type: couchbase
      memoryQuota: 128
      replicas: $CLUSTER_REPLICAS
      ioPriority: high
      evictionPolicy: fullEviction
      conflictResolution: seqno
      enableFlush: true
      enableIndexReplica: false
  servers:
    - size: 5
      name: all_services
      services:
        - data
        - index
        - query
        - search
      dataPath: /opt/couchbase/var/lib/couchbase/data
      indexPath: /opt/couchbase/var/lib/couchbase/data
