apiVersion: batch/v1
kind: Job
metadata:
  name: pillowfight
spec:
  template:
    metadata:
      name: pillowfight
    spec:
      containers:
      - name: pillowfight
        image: sequoiatools/pillowfight:v5.0.1
        command: ["cbc-pillowfight",
                  "-U", "couchbaseAdmin://cb-cluster-member-0000.default.svc.cluster.local/default?select_bucket=true",
                  "-I", "10000", "-P", "longpass32d"]
      restartPolicy: Never
