application_api_version: v1beta1
properties:
  operatorServiceAccount:
    type: string
    title: Operator Service Account
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups:
            - couchbase.com
            resources:
            - couchbaseclusters
            verbs:
            - "*"
          - apiGroups:
            - storage.k8s.io
            resources:
            - storageclasses
            verbs:
            - "get"
          - apiGroups:
            - apiextensions.k8s.io
            resources:
            - customresourcedefinitions
            verbs:
            - "*"
          - apiGroups:
            - ""
            resources:
            - pods
            - services
            - endpoints
            - persistentvolumeclaims
            - events
            - secrets
            verbs:
            - "*"
          - apiGroups:
            - ""
            resources:
            - persistentvolumes
            verbs:
            - "get"
            - "watch"
          - apiGroups:
            - apps
            resources:
            - deployments
            verbs:
            - "*"
  dbUsername:
    type: string
    title: Administrator Username
    default: "Administrator"
    x-google-marketplace:
      type: STRING
      string:
        generatedProperties:
          base64Encoded: dbUsernameBase64
  dbPassword:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 16
  couchbaseOperatorImage:
    type: string
    default: gcr.io/couchbase-dev/k8s/operator:1.1.0
    x-google-marketplace:
      type: IMAGE
  initialDelaySeconds:
    title: Initial Delay in Seconds
    type: integer
    default: 30
    minimum: 1
    maximum: 5000
  periodSeconds:
    title: Period Delay in Seconds
    type: integer
    default: 5
    minimum: 1
    maximum: 5000
  autoFailoverTimeout:
    title: Auto Failover Timeout
    type: integer
    default: 5
    minimum: 1
    maximum: 5000
  autoFailoverMaxCount:
    title: Auto Failover Max Count
    type: integer
    default: 3
    minimum: 3
    maximum: 5000
  autoFailoverODDI:
    title: Auto Failover On Data Disk Issue
    type: boolean
    default: true
  autoFailoverODDITP:
    title: Auto Failover On Data Disk Issue Time Period 
    type: integer
    default: 120
    minimum: 5
    maximum: 5000
  autoFailoverServerGroup:
    title: Auto Failover Server Group 
    type: boolean
    default: false
  failureThreshold:
    title: Failure Threshold
    type: integer
    default: 19
    minimum: 1
    maximum: 5000
  servers:
    title: Number of Couchbase Servers
    type: integer
    default: 3
    minimum: 1
    maximum: 300
  clusterReplicas:
    title: Couchbase Cluster Replicas
    type: integer
    default: 2
    minimum: 1
    maximum: 300
  containerPort:
    title: Container Port
    type: integer
    default: 8080
    minimum: 1024
    maximum: 65535
  bucketMemoryQuota:
    title: Bucket Memory Quota
    type: integer
    default: 256
    minimum: 256
    maximum: 2147483647
  dataServiceMemoryQuota:
    title: Data Service Memory Quota
    type: integer
    default: 256
    minimum: 256
    maximum: 2147483647
  indexServiceMemoryQuota:
    title: Index Service Memory Quota
    type: integer
    default: 256
    minimum: 256
    maximum: 2147483647
  searchServiceMemoryQuota:
    title: Search Service Memory Quota
    type: integer
    default: 256
    minimum: 256
    maximum: 2147483647
  eventingServiceMemoryQuota:
    title: Search Service Memory Quota
    type: integer
    default: 256
    minimum: 256
    maximum: 2147483647
  analyticsServiceMemoryQuota:
    title: Search Service Memory Quota
    type: integer
    default: 1024
    minimum: 1024
    maximum: 2147483647
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  storeClass:
    type: string
    x-google-marketplace:
      type: STORAGE_CLASS
      storageClass:
        type: SSD
  # reportingSecret:
   # type: string
   # x-google-marketplace:
   #   type: REPORTING_SECRET
required:
- dbUsername
- dbPassword
- containerPort
- couchbaseOperatorImage
- initialDelaySeconds
- periodSeconds
- autoFailoverTimeout
- autoFailoverMaxCount
- autoFailoverODDI
- autoFailoverODDITP
- autoFailoverServerGroup
- failureThreshold
- servers
- clusterReplicas
- bucketMemoryQuota
- dataServiceMemoryQuota
- indexServiceMemoryQuota
- searchServiceMemoryQuota
- eventingServiceMemoryQuota
- analyticsServiceMemoryQuota
- name
- namespace
- storeClass
# - reportingSecret
