application_api_version: v1beta1
properties:
  operatorServiceAccount:
    type: string
    title: Operator Service Account
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups:
            - couchbase.database.couchbase.com
            resources:
            - couchbaseclusters
            verbs:
            - "*"
          - apiGroups:
            - apiextensions.k8s.io
            resources:
            - customresourcedefinitions
            verbs:
            - "*"
          - apiGroups:
            - ""
            resources:
            - pods
            - services
            - endpoints
            - persistentvolumeclaims
            - events
            - secrets
            verbs:
            - "*"
          - apiGroups:
            - apps
            resources:
            - deployments
            verbs:
            - "*"
  dbUsername:
    type: string
    title: Administrator Username
    default: "Administrator"
    x-google-marketplace:
      type: STRING
      string:
        generatedProperties:
          base64Encoded: dbUsernameBase64
  dbPassword:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 16
  couchbaseOperatorImage:
    type: string
    default: gcr.io/couchbase-dev/k8s/operator:1.0
    x-google-marketplace:
      type: IMAGE
  initialDelaySeconds:
    title: Initial Delay in Seconds
    type: integer
    default: 30
    minimum: 1
    maximum: 5000
  periodSeconds:
    title: Period Delay in Seconds
    type: integer
    default: 5
    minimum: 1
    maximum: 5000
  failureThreshold:
    title: Failure Threshold
    type: integer
    default: 19
    minimum: 1
    maximum: 5000
  operatorReplicas:
    title: Operator replicas
    type: integer
    default: 1
    minimum: 1
    maximum: 10
  clusterReplicas:
    title: Couchbase Cluster Replicas
    type: integer
    default: 3
    minimum: 1
    maximum: 300
  containerPort:
    title: Container Port
    type: integer
    default: 8080
    minimum: 1024
    maximum: 65535
  dataServiceMemoryQuota:
    title: Data Service Memory Quota
    type: integer
    default: 256
    minimum: 256
    maximum: 2147483647
  indexServiceMemoryQuota:
    title: Index Service Memory Quota
    type: integer
    default: 256
    minimum: 256
    maximum: 2147483647
  searchServiceMemoryQuota:
    title: Search Service Memory Quota
    type: integer
    default: 256
    minimum: 256
    maximum: 2147483647
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  # reportingSecret:
   # type: string
   # x-google-marketplace:
   #   type: REPORTING_SECRET
required:
- dbUsername
- dbPassword
- containerPort
- couchbaseOperatorImage
- initialDelaySeconds
- periodSeconds
- failureThreshold
- operatorReplicas
- clusterReplicas
- dataServiceMemoryQuota
- indexServiceMemoryQuota
- searchServiceMemoryQuota
- name
- namespace
# - reportingSecret
